# Renombrar columnas a camelCase

Este notebook estandariza los nombres de las columnas del dataset
al formato camelCase para mantener consistencia en los procesos
de limpieza y modelado de datos.

In [16]:
# Importando Librerías
import pandas as pd
import re

In [17]:
# cargar el dataset
df = pd.read_csv("../../data/processed/gym_churn_cleaned_2.csv")
df.head()

,idClient,gender,nearLocation,partner,promoFriends,phone,contractPeriod,groupVisits,age,avgAdditionalChargesTotal,monthToEndContract,lifetime,avgClassFrequencyTotal,avgClassFrequencyCurrentMonth,churn
0,1,1,1,1,1,0,6,1,29,14.227470,5,3,0.020398,0.000000,0
1,2,0,1,0,0,1,12,1,31,113.202938,12,7,1.922936,1.910244,0
2,3,0,1,1,0,1,1,0,28,129.448479,1,2,1.859098,1.736502,0
3,4,0,1,1,1,1,12,1,33,62.669863,12,2,3.205633,3.357215,0
4,5,1,1,1,1,1,1,0,26,198.362265,1,3,1.113884,1.120078,0

In [18]:
# Función CamelCase
def a_camel_case(columna):
    # Si ya es camelCase, la dejamos
    if columna[0].islower() and any(c.isupper() for c in columna[1:]):
        return columna

    # Reemplazar separadores por espacios
    columna = re.sub(r'[_\-]+', ' ', columna)
    columna = re.sub(r'[^a-zA-Z0-9 ]', '', columna)

    partes = columna.lower().split()
    return partes[0] + ''.join(p.capitalize() for p in partes[1:])

In [20]:
ruta_salida = "../../data/processed/gym_churn_camelcase.csv"

df.to_csv(ruta_salida, index=False)

print(f"Dataset guardado correctamente en: {ruta_salida}")

Dataset guardado correctamente en: ../../data/processed/gym_churn_camelcase.csv

In [21]:
pd.read_csv(ruta_salida).head()

,idClient,gender,nearLocation,partner,promoFriends,phone,contractPeriod,groupVisits,age,avgAdditionalChargesTotal,monthToEndContract,lifetime,avgClassFrequencyTotal,avgClassFrequencyCurrentMonth,churn
0,1,1,1,1,1,0,6,1,29,14.227470,5,3,0.020398,0.000000,0
1,2,0,1,0,0,1,12,1,31,113.202938,12,7,1.922936,1.910244,0
2,3,0,1,1,0,1,1,0,28,129.448479,1,2,1.859098,1.736502,0
3,4,0,1,1,1,1,12,1,33,62.669863,12,2,3.205633,3.357215,0
4,5,1,1,1,1,1,1,0,26,198.362265,1,3,1.113884,1.120078,0